<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Ze92xP\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Ze92xP/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Ze92xP.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Ze92xP\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container0Ze92xP\appAppKernelDevDebugContainer([
    'container.build_hash' => '0Ze92xP',
    'container.build_id' => '595313dd',
    'container.build_time' => 1771910523,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Ze92xP');
