<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @Modules/ps_distributionapiclient/vue-app/components.d.ts */
class __TwigTemplate_02134125e92821275d4657dd90076f59 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_5a27a8ba21ca79b61932376b2fa922d2 = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->enter($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@Modules/ps_distributionapiclient/vue-app/components.d.ts"));

        $__internal_6f47bbe9983af81f1e7450e9a3e3768f = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_6f47bbe9983af81f1e7450e9a3e3768f->enter($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@Modules/ps_distributionapiclient/vue-app/components.d.ts"));

        // line 1
        echo "/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PuikAvatar: typeof import('@prestashopcorp/puik-components')['PuikAvatar']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik-components')['PuikCard']
    PuikIcon: typeof import('@prestashopcorp/puik-components')['PuikIcon']
    PuikLink: typeof import('@prestashopcorp/puik-components')['PuikLink']
    PuikModal: typeof import('@prestashopcorp/puik-components')['PuikModal']
    PuikTable: typeof import('@prestashopcorp/puik-components')['PuikTable']
    PuikTag: typeof import('@prestashopcorp/puik-components')['PuikTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
";
        
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->leave($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof);

        
        $__internal_6f47bbe9983af81f1e7450e9a3e3768f->leave($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof);

    }

    public function getTemplateName()
    {
        return "@Modules/ps_distributionapiclient/vue-app/components.d.ts";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PuikAvatar: typeof import('@prestashopcorp/puik-components')['PuikAvatar']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik-components')['PuikCard']
    PuikIcon: typeof import('@prestashopcorp/puik-components')['PuikIcon']
    PuikLink: typeof import('@prestashopcorp/puik-components')['PuikLink']
    PuikModal: typeof import('@prestashopcorp/puik-components')['PuikModal']
    PuikTable: typeof import('@prestashopcorp/puik-components')['PuikTable']
    PuikTag: typeof import('@prestashopcorp/puik-components')['PuikTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
", "@Modules/ps_distributionapiclient/vue-app/components.d.ts", "/var/www/html/modules/ps_distributionapiclient/vue-app/components.d.ts");
    }
}
