services:
  db:
    image: mysql:8.0
    container_name: presta_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:8
    container_name: presta_app
    restart: always
    ports:
      - "8085:80"
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
    depends_on:
      - db
    volumes:
    - ./prestashop_data:/var/www/html

volumes:
  db_data:
