<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkn5HqehGH73mewn0qZYJ'."\n".'/2Ew943uSvn3xQgpOniUF3nX5HtlBZTjzYqJ0KqjWf4jSmfRw6ph7gjGLu8ZEZc9'."\n".'MPOfewL67BFRn697vAhW28mCQp+wVvXa4rEfWcJyUtMj6Idk6eJC+g6y2quZ+fj2'."\n".'vejbCrPwa6Ma83qBvqubu+54OIRwiln2w4yOcTQ5BpVMcfMP+5m2r37OV4rRFWSA'."\n".'UE3FI8FFySFfFay8b0uPpoksu4LUfWxLqa/8lhnACVVIBfky9hAguVcakXRI+XaX'."\n".'ewtwJ9HFI4qTI9NAdRppyAAf0GN+/c7xyzn9EcvuyqwP3FmLqys6tSR9KxFZjFeW'."\n".'DwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
