<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUGxuq4U\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUGxuq4U/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerUGxuq4U.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerUGxuq4U\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerUGxuq4U\appAppKernelProdContainer([
    'container.build_hash' => 'UGxuq4U',
    'container.build_id' => '565b5171',
    'container.build_time' => 1771898162,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUGxuq4U');
